### ISSUE TITLE
Continue work on the UI's assets.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#15]

**Comment by Axelxion** [comment]
I decided to get all of the drink and shelving items started for asset design

**Comment by Axelxion** [comment]
![ice](https://user-images.githubusercontent.com/91759335/137417330-a4b216ad-4987-4a4d-911a-0e931225984d.jpg)
![tap](https://user-images.githubusercontent.com/91759335/137417331-d7b599a3-c137-4e7d-95c9-d4a2b1995873.jpg)

**Comment by Axelxion** [comment]
![naranja](https://user-images.githubusercontent.com/91759335/137435291-d01d9367-6540-4246-aba1-17333859aa13.png)
![limon](https://user-images.githubusercontent.com/91759335/137435292-374f3dc0-3e84-4dff-96a1-68f0d623c015.png)
![pit](https://user-images.githubusercontent.com/91759335/137435294-1753f964-6013-4e4d-b4d7-013952a52e69.png)
![rummy](https://user-images.githubusercontent.com/91759335/137435295-bc087ac4-338a-451c-b2d6-7bd518260298.png)
![vod](https://user-images.githubusercontent.com/91759335/137435296-e1df7baa-495a-4850-9d9c-c623aaa6afb1.png)
![pineapp](https://user-images.githubusercontent.com/91759335/137435298-4f9b53f5-026d-4080-b788-c003c2b1809e.png)
![taps](https://user-images.githubusercontent.com/91759335/137435299-dd664a9e-d476-40b7-bbdb-4d27d8ce6bb3.png)
![iceb](https://user-images.githubusercontent.com/91759335/137435300-38d5d250-c1f5-46eb-9f47-cc23ba73e378.png)

**Comment by Axelxion** [comment]
![shelf](https://user-images.githubusercontent.com/91759335/138368941-c566bf91-1bc4-4e44-ba3f-f0905125c8ac.png)
![shake](https://user-images.githubusercontent.com/91759335/138368942-6c57c016-f580-406c-8fd4-e26f90545e8b.png)
![beer](https://user-images.githubusercontent.com/91759335/138368945-39acfc31-8768-49d0-8c3d-2fa04e8b6b5a.png)
![whisk](https://user-images.githubusercontent.com/91759335/138368946-d35a654f-c1a3-4a14-9d34-05fb6f686169.png)

**Comment by Axelxion** [comment]
![mint](https://user-images.githubusercontent.com/91759335/140441252-4af8db99-7935-46ec-8b39-4a1c4738725c.png)
![vodkaaa](https://user-images.githubusercontent.com/91759335/140441264-4e70eb00-d45b-47d3-a0e1-6126b6e74b72.png)
![drink](https://user-images.githubusercontent.com/91759335/140441272-55ab3b89-bc7c-425f-9cb8-2026ce3acfa1.png)

**Comment by Axelxion** [comment]
![bebery](https://user-images.githubusercontent.com/91759335/140444716-7ec5debb-70f8-44db-a9ad-0f423c5b6318.png)

**Comment by Axelxion** [comment]
![bourbon](https://user-images.githubusercontent.com/91759335/141387800-49ed2f22-36c6-49d0-bd16-74e74eaf0aa1.png)
updated bourbon bottle for sizing

**Comment by Axelxion** [comment]
![Vodkaa](https://user-images.githubusercontent.com/91759335/141387847-50f6875b-dfd4-4597-bc47-a474162f7dd4.png)
vodka with a label in case it is needed

**Comment by dantogno** [comment]
@Axelxion Thanks for adding all the updates here!

**Comment by Axelxion** [comment]
Forgot i still had to redo the rum and make the gin bottle. got one more thing to do for this after but that's it

**Comment by Axelxion** [comment]
![rrrum](https://user-images.githubusercontent.com/91759335/144524389-1cdd75b8-02d6-4851-9a48-8bee2eed3bd2.png)
![gintext](https://user-images.githubusercontent.com/91759335/144524391-14a7f9b5-6d10-4a72-ba11-c968536f1f72.png)
![gin](https://user-images.githubusercontent.com/91759335/144524392-aba4f1ba-b7da-4116-9281-7372753b27b1.png)

**Comment by Axelxion** [comment]
![pine](https://user-images.githubusercontent.com/91759335/145496772-643d1fb6-38e6-4a4f-b933-e7ddb2872805.png)
