### ISSUE TITLE
Add indicator for text advancement.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#29]
Implement the text advancement arrow asset to indicate when the player can advance the text.

**Comment by Axelxion** [comment]
![Untitled_Artwork](https://user-images.githubusercontent.com/91759335/140441079-5d882bfc-5361-4f74-92ff-cca757a47466.gif)
Collab with Jude

**Comment by mike12699** [comment]
Text indicator now shows up during normal gameplay when the player advances the dialogue.

https://user-images.githubusercontent.com/44095303/141384254-a2cb86b8-6902-44de-a05b-34f3e8d46418.mp4
