### ISSUE TITLE
Touch up on the programming of the mix/serve and reset buttons.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#32]

**Comment by mike12699** [comment]
I made changes and let the "Mix" button to display a confirmation panel which serves the drink and tosses it. Serving the drink will result in the branching scenarios where Shaw will either like or dislike the drink. Tossing the drink will reset the ingredients and let the player start over.

https://user-images.githubusercontent.com/44095303/140418755-3500c24f-cf7e-4560-baa3-58b6b9d44fec.mp4
