### ISSUE TITLE
Create the conversation assets for Valyria.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#33]

**Comment by mike12699** [comment]
Valeria's scenario will now be activated upon completion of the previous character's scenario. This will also affect upcoming characters as well.

https://user-images.githubusercontent.com/44095303/142468474-61b6d3e6-59fa-4abd-8920-91dd0945b621.mp4

**Comment by mike12699** [comment]
Conversation assets for Valyria are now fully implemented, and sprites change accordingly.

https://user-images.githubusercontent.com/44095303/144503426-ddd1d62a-0cba-4ae2-aea1-c69fb3300dbe.mp4
