### ISSUE TITLE
Create a choice box asset for the UI.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#35]

**Comment by Axelxion** [comment]
![chocie](https://user-images.githubusercontent.com/91759335/140441164-49306601-ccd9-42e9-9bcd-e700be30e612.png)
![choice](https://user-images.githubusercontent.com/91759335/140441165-09ee75d1-2da2-4d7d-af60-2a441857ca16.png)
choice box and button
