### ISSUE TITLE
Render Shaw's Expressions.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#39]
Shade Shaw's expressions and add finishing touches.

**Comment by iscarium** [comment]
![Shaw_Concern](https://user-images.githubusercontent.com/91701261/141387102-fd992ba3-3323-4e68-b0d8-e3ca7733958d.png)
![Shaw_Grumpy](https://user-images.githubusercontent.com/91701261/141387103-1633bda5-5310-41c0-a57e-790e6433e8ae.png)
![Shaw_Neutral](https://user-images.githubusercontent.com/91701261/141387104-c12b272f-40b3-49ea-8bd3-33465c982697.png)
![Shaw_Pleased](https://user-images.githubusercontent.com/91701261/141387105-4fdbadaf-2305-4ded-89f8-22456d167496.png)
![Shaw_Shy](https://user-images.githubusercontent.com/91701261/141387107-e47eaf0d-ce49-498a-ab20-cdad4e71a468.png)
