### ISSUE TITLE
Draw and render the Mind Melter's sprite.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#40]
Draw and render the Mind Melter's sprite for implementation on the "serve this drink" interface.

**Comment by Axelxion** [comment]
![notad](https://user-images.githubusercontent.com/91759335/141387429-278feb06-5aa8-4960-99a2-9b2309502e20.png)
![tad](https://user-images.githubusercontent.com/91759335/141387430-8a3b1463-90da-4002-8027-0c53534aee25.png)
Here are the two finals, one with little tadpoles and one without. I believe we agreed on doing the second one. They can be interchangeable.
