### ISSUE TITLE
Polish the choice box UI asset to properly resize in-engine.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#41]

**Comment by Axelxion** [comment]
![newframe](https://user-images.githubusercontent.com/91759335/141387669-4b6734f9-76a6-4d31-a530-7a7c61550720.png)
Here was the first one I did that I messed up the sizing because of my own wording of the question

**Comment by Axelxion** [comment]
![button](https://user-images.githubusercontent.com/91759335/141387705-79d35912-4226-4d06-8e3e-c19330d75437.png)
![frame](https://user-images.githubusercontent.com/91759335/141387707-cc275e2f-bcd5-470c-aae2-036a134f5687.png)
And here are the final products for the choice box and buttons
