### ISSUE TITLE
Create code for transitioning from Shaw to Valeria.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#45]

**Comment by mike12699** [comment]
I implemented a transition that would let the player continue onto the next character. After finishing up the dialogue with the previous character, a new panel will open confirming the player to go on to the next part. Doing so will display the next character along with the drink system.

https://user-images.githubusercontent.com/44095303/142467965-68744d13-1f1e-438d-ad44-de312d7f52b1.mp4
