### ISSUE TITLE
Create the remaining drink and ingredient assets.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#62]

**Comment by Axelxion** [comment]
![potion](https://user-images.githubusercontent.com/91759335/145489332-4d7998f3-e53a-46f5-bed2-08ea7b1ac0f5.png)
![pine](https://user-images.githubusercontent.com/91759335/145489348-d73817de-7144-4c39-8765-a1444dcfe6e2.png)

**Comment by Axelxion** [comment]
![mix](https://user-images.githubusercontent.com/91759335/145496822-601c3d9f-48a4-4f60-affd-d76d178cf4cf.png)
![page](https://user-images.githubusercontent.com/91759335/145496823-ff183f08-e7b3-4d82-9e89-8ae45972811d.png)
