### ISSUE TITLE
Fix sound not playing errors.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#67]

**Comment by mike12699** [comment]
I added the remaining sounds to the UI assets whenever they are triggered to play a sound. In addition, I added a slide animation to the recipe book to give the game more appeal. When closing the book, opening it back up again will view the last page that was seen by the player.

https://user-images.githubusercontent.com/44095303/146471197-f363c67b-7c48-414e-9c91-94faaeb7bdd3.mp4
