### ISSUE TITLE
Make an edit of the background image.

### ISSUE THREAD

**Issue by KeaporaTheOwl** [mike12699/project_tavern#69]

**Comment by Axelxion** [comment]
Here's the start of the mockups, mainly just adding to each one. the first is a sample of what we have now

**Comment by Axelxion** [comment]
![#1](https://user-images.githubusercontent.com/91759335/145659491-389fce66-5093-475d-ad1d-552f95024523.png)
![#2](https://user-images.githubusercontent.com/91759335/145659493-8edcedb1-5b39-49bd-8fce-279236c76593.png)
![#3](https://user-images.githubusercontent.com/91759335/145659494-d118f1db-f39d-4860-b801-2c1933308980.png)
![#4](https://user-images.githubusercontent.com/91759335/145659496-e6a696a0-fbe3-4cc2-8c83-ada4a20338f5.png)
![#5](https://user-images.githubusercontent.com/91759335/145659498-4a175251-67e6-4d0e-b0ce-a8de9d4b5df6.png)
![#6](https://user-images.githubusercontent.com/91759335/145659499-d396b232-90a0-42e0-9b1c-c8a31c43acd5.png)
![#7](https://user-images.githubusercontent.com/91759335/145659500-a76125e1-87cb-473f-9d1c-f5aa54d693a5.png)
![#8](https://user-images.githubusercontent.com/91759335/145659501-7cf3f69b-ea8b-41f8-85bb-171c40230cc0.png)
![#9](https://user-images.githubusercontent.com/91759335/145659503-63b8b360-f313-4365-a9fc-f711c32b13a7.png)
![#10](https://user-images.githubusercontent.com/91759335/145659506-6a795c5e-3a61-46a5-9576-ec1537d72f85.png)
![#11](https://user-images.githubusercontent.com/91759335/145659508-a78f3074-f33d-4ac9-a91b-1d64727d8600.png)
![#12](https://user-images.githubusercontent.com/91759335/145659509-f65b1a9c-9e98-4f3f-b616-21d8b653a8f7.png)
![#13](https://user-images.githubusercontent.com/91759335/145659510-161de442-8e03-4ab0-962c-7ccd914eba4e.png)
![#14](https://user-images.githubusercontent.com/91759335/145659511-df1108ce-482a-4d83-8783-602c410b83b9.png)
![#15](https://user-images.githubusercontent.com/91759335/145659512-e07e2752-4e01-4f95-8220-aedc19a287a2.png)
![#16](https://user-images.githubusercontent.com/91759335/145659513-27af10de-0d42-47cc-ad74-e6255fd1064e.png)
![#17](https://user-images.githubusercontent.com/91759335/145659514-969115ca-c25b-4a79-9c9b-bdd731f8da19.png)
![#18](https://user-images.githubusercontent.com/91759335/145659515-a4e8bdd0-130f-4223-9783-a0a027f7a8a5.png)
![#19](https://user-images.githubusercontent.com/91759335/145659516-97661f21-4203-4ea4-aa48-571e9e99462f.png)
![#20](https://user-images.githubusercontent.com/91759335/145659518-7c6949bc-9965-4196-accc-080b75260fa2.png)
![#21](https://user-images.githubusercontent.com/91759335/145659519-636738ba-8531-4d98-8881-9fb371f7dcbd.png)

**Comment by Axelxion** [comment]
Here is the final product with and without a character
![bg22](https://user-images.githubusercontent.com/91759335/146277449-c555630e-4092-443b-85aa-dce6e630452c.png)
![finalbg](https://user-images.githubusercontent.com/91759335/146277462-930d8d9c-0026-431f-b4bf-119b0d28ae66.png)
